version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./docker/php
            dockerfile: php-fpm.docker
        environment:
            PHP_IDE_CONFIG: serverName=laravel_daily_livewire
        volumes:
            - .:/app
        depends_on:
            - db
    php-cli:
        build:
            context: ./docker/php
            dockerfile: php-cli.docker
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: mysql:8
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_daily_livewire
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3306:3306"
    node-watch:
        build:
            context: ./docker/node
        volumes:
            - .:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    node-cli:
        build:
            context: ./docker/node
        volumes:
            - .:/app
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - "8025:8025"
volumes:
    db:
